"""集中维护 MiniMax H3 的公开接口常量和项目默认值。"""

from __future__ import annotations

FPS = 24
MODEL_ID = "MiniMaxAI/MiniMax-H3"
H3_MIN_SECONDS = 5.0
H3_MAX_SECONDS = 15.0
H3_FRAME_STRIDE = 17
H3_FRAME_OFFSET = 5
H3_MAX_ALIGNED_FRAMES = (
    H3_FRAME_OFFSET
    + ((int(H3_MAX_SECONDS * FPS) - H3_FRAME_OFFSET) // H3_FRAME_STRIDE) * H3_FRAME_STRIDE
)
H3_SAFE_CHUNK_SECONDS = H3_MAX_ALIGNED_FRAMES / FPS

H3_MAX_IMAGES = 9
H3_MAX_VIDEOS = 3
H3_MAX_AUDIOS = 3
H3_MAX_REFERENCES = 12
MAX_PROMPT_CHARS = 6800
DEFAULT_DURATION_SECONDS = 60.0
DEFAULT_CHUNK_COUNT = 5
DEFAULT_SEED = 20260920
DEFAULT_HEIGHT = 768
DEFAULT_WIDTH = 1344

